import uuid
from contextlib import AbstractContextManager
from typing import Callable

from fastapi import HTTPException, status
from sqlalchemy.orm import Session

from app.models.supplier import Supplier, SupplierStatus
from app.repositories.supplier_repository import SupplierRepository
from app.schemas.supplier import SupplierCreate, SupplierUpdate


class SupplierService:
    def __init__(self, session_factory: Callable[[], AbstractContextManager[Session]]) -> None:
        self.repo = SupplierRepository(session_factory)

    # ── Create ────────────────────────────────────────────────────────────────

    def create(self, payload: SupplierCreate) -> Supplier:
        supplier = Supplier(
            id=uuid.uuid4(),
            legal_name=payload.legal_name,
            trade_name=payload.trade_name,
            email=payload.email,
            mobile_number=payload.mobile_number,
            address_line1=payload.address_line1,
            city=payload.city,
            province=payload.province,
            postal_code=payload.postal_code,
            country=payload.country,
            status=SupplierStatus.DRAFT,
            # supplier_code is generated by the DB sequence — do NOT pass it here
        )
        return self.repo.create(supplier)

    # ── Read ──────────────────────────────────────────────────────────────────

    def get_or_404(self, supplier_id: uuid.UUID) -> Supplier:
        supplier = self.repo.get(supplier_id)
        if supplier is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Supplier not found.",
            )
        return supplier

    def list(
        self,
        *,
        skip: int = 0,
        limit: int = 20,
        filter_status: SupplierStatus | None = None,
        q: str | None = None,
    ) -> tuple[list[Supplier], int]:
        items = self.repo.list(skip=skip, limit=limit, status=filter_status, q=q)
        total = self.repo.count(status=filter_status, q=q)
        return items, total

    # ── Update ────────────────────────────────────────────────────────────────

    def update(self, supplier_id: uuid.UUID, payload: SupplierUpdate) -> Supplier:
        self.get_or_404(supplier_id)
        data = payload.model_dump(exclude_unset=True)
        return self.repo.update(supplier_id, data)

    def update_status(self, supplier_id: uuid.UUID, new_status: SupplierStatus) -> Supplier:
        self.get_or_404(supplier_id)
        return self.repo.update_status(supplier_id, new_status)
